### PR TITLE
Reorderable elements

### PR DESCRIPTION
**Pull request by Mukarillo**
-Making Preview Results Rows reorderable issue #162
-Pinging object when you click the row

<p align="center">
  example
</p>

### CODE REVIEW

**Comment by Mukarillo** [comment]
In this last commit I added the ability to resize the preview columns by dragging the divisors
<p align="center">
  example
</p>

**Comment by edwardrowe** [comment]
You're a wizard. This looks perfect.

**Comment by Mukarillo** [comment]
Haha, thanks man :)

**Comment by edwardrowe** [comment]
Overall this is great. You've made the code cleaner which is awesome (ex: creating PreviewRowResult class, naming some magic numbers).

Gonna merge this into the Develop branch and fix up a few things. I may make Issues for these, if they are a bunch of work. I'll let you know what I'm gonna fix in case you are looking for something to do but no pressure at all!

Here's my list:

* Pinging:
    * Resizing doesn’t seem to work if clicking a row (it pings instead of letting me resize). The fix would be to throw out the ping if clicking on the resize divider, or changing the ping clickable area. I debated about a button for pinging but there are already a lot of buttons.
    * Pings object if you click a disabled button (arrows on elements at top or bottom of the list)
* Resizing:
    * Increase padding on resize bar (add space between text and divider on 2nd and 3rd columns)
        * This might also give it a bigger “hotspot”, which It could use.
    * If you release while not on top of the bar (due to sizing maxing out I think?), it won’t realize you lifted, you have to click again to toggle it as done resizing.
        * Or maybe it’s if you alt tab while it’s down… need to dig into this more?
    * Does the divider sliding lag the cursor a frame? I'll want to look into the update order.
    * Feature (this could be spun into an Issue for a future fix) Double click to resize to columns to max length?
* Scrolling the preview panel seems broken? (Vertically and horizontally)
* If you undo “preview steps” and then redo it, columns break
    * It should remember the widths you chose, preferably
        * Should these be serialized? EditorPrefs.
* Resizing the first column should push the second column by the same amount
* “this” should be used more. (This is a style thing that I am still not sure about but it's the style so I do it.)
* Toggle functions should just be called Set. Personal preference thing but I'd use Toggle for things that are stateful, and remember their "on/off" state. Toggle() would take no parameters and just flip it. But I like the way these work so I'd just make them Set(bool)

**Comment by Mukarillo** [comment]
Hey @edwardrowe, I saw that u done some of the changes in the development branch.
I would like to help with this fixes. Should I just keep developing in this branch and send a PR?

**Comment by edwardrowe** [comment]
Yeah if you want to do any work for now you can fork / work out if
develop-v1.7.0

Once we finish these up I'll make a new release.

**Comment by Mukarillo** [comment]
I just sent a [PR](https://github.com/redbluegames/unity-mulligan-renamer/pull/212) with some fixes.

I coudn't reproduce this one:
_`If you release while not on top of the bar (due to sizing maxing out I think?), it won’t realize you lifted, you have to click again to toggle it as done resizing.
Or maybe it’s if you alt tab while it’s down… need to dig into this more?`_

I am not sure if I got this one right, but I don't think dragging the bars create lags. We are just re-drawing the screen with different column sizes.
_`Does the divider sliding lag the cursor a frame? I'll want to look into the update order.`_

Tomorrow I will start investigating this one:
_`Scrolling the preview panel seems broken? (Vertically and horizontally)`_

Do you mind sharing the steps to reproduce this one? I didn't understood how to do it
_`If you undo “preview steps” and then redo it, columns break
It should remember the widths you chose, preferably
Should these be serialized? EditorPrefs.`_

**Comment by edwardrowe** [comment]
Ugh sorry I can't reproduce the first one either (re: having to click down again after unfocusing the window, or something). I'll have to keep experimenting or maybe I was just mistaken.

On second look, I think sliding is pretty much good. I may have been seeing the flickering in #218.

Preview steps is tasked as #213

**Pull request merged**
